export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "primary-container": "#f7d002",
                "surface-container-low": "#f2f4f6",
                "on-tertiary-fixed-variant": "#474746",
                "on-secondary": "#ffffff",
                "outline-variant": "#d0c6ab",
                "on-tertiary-fixed": "#1b1c1c",
                "on-secondary-fixed-variant": "#00530e",
                "on-primary-fixed": "#221b00",
                "on-error": "#ffffff",
                "inverse-primary": "#e9c400",
                "background": "#f8f9fb",
                "on-tertiary": "#ffffff",
                "outline": "#7e775f",
                "surface-variant": "#e0e3e5",
                "error-container": "#ffdad6",
                "primary-fixed-dim": "#e9c400",
                "surface-container": "#eceef0",
                "on-primary": "#ffffff",
                "on-secondary-fixed": "#002203",
                "secondary-fixed": "#8ffb87",
                "on-surface": "#191c1e",
                "primary-fixed": "#ffe16e",
                "tertiary-fixed": "#e5e2e1",
                "on-background": "#191c1e",
                "tertiary-container": "#d5d2d2",
                "tertiary-fixed-dim": "#c8c6c5",
                "inverse-surface": "#2d3133",
                "secondary-container": "#8ffb87",
                "on-tertiary-container": "#5b5a5a",
                "surface-bright": "#f8f9fb",
                "on-secondary-container": "#007518",
                "surface-container-highest": "#e0e3e5",
                "on-surface-variant": "#4d4632",
                "primary": "#705d00",
                "surface": "#f8f9fb",
                "surface-container-high": "#e6e8ea",
                "surface-container-lowest": "#ffffff",
                "secondary": "#0c831f",
                "on-error-container": "#93000a",
                "surface-dim": "#d8dadc",
                "on-primary-container": "#6b5900",
                "error": "#ba1a1a",
                "inverse-on-surface": "#eff1f3",
                "on-primary-fixed-variant": "#544600",
                "secondary-fixed-dim": "#74dd6e",
                "tertiary": "#5f5e5e",
                "surface-tint": "#705d00",
                "blinkit-green": "#0c831f",
                "blinkit-yellow": "#f7d002"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "base": "4px",
                "gutter": "12px",
                "md": "16px",
                "xs": "4px",
                "xl": "32px",
                "margin-mobile": "16px",
                "lg": "24px",
                "sm": "8px"
            },
            "fontFamily": {
                "headline-md": ["Inter"],
                "label-sm": ["Inter"],
                "display-lg": ["Inter"],
                "label-lg": ["Inter"],
                "body-lg": ["Inter"],
                "headline-lg": ["Inter"],
                "body-sm": ["Inter"],
                "title-lg": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-md": ["Inter"]
            },
            "fontSize": {
                "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
                "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
                "title-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
                "headline-lg-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "700" }],
                "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
            }
        }
    }
}
